package main

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type AsymmetricalKind byte

const (
	RsaKind AsymmetricalKind = iota
	InvalidAsymmetricalKind
)

func ConvertInteger2AsymmetricalKind[T constraints.Integer](v T) AsymmetricalKind {
	return AsymmetricalKind(v)
}

func (k AsymmetricalKind) AssertKind(kinds string) AsymmetricalKind {
	for _, kind := range k.Kinds() {
		if strings.ToLower(kinds) == strings.ToLower(kind.String()) {
			return kind
		}
	}
	return InvalidAsymmetricalKind
}

func (k AsymmetricalKind) String() string {
	switch k {
	case RsaKind:
		return "Rsa"
	default:
		return "InvalidAsymmetricalKind"
	}
}

func (k AsymmetricalKind) Keys() []string {
	return []string{
		"Rsa",
		"InvalidAsymmetricalKind",
	}
}

func (k AsymmetricalKind) Kinds() []AsymmetricalKind {
	return []AsymmetricalKind{
		RsaKind,
		InvalidAsymmetricalKind,
	}
}

func (k AsymmetricalKind) SvgFileName() string {
	switch k {
	case RsaKind:
		return "Rsa"
	default:
		return "InvalidAsymmetricalKind"
	}
}
