package main

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type CryptNodeKind byte

const (
	SymmetryNodeKind CryptNodeKind = iota
	AsymmetricalNodeKind
	HashNodeKind
	EncodingNodeKind
	ToolNodeKind
	InvalidCryptNodeKind
)

func ConvertInteger2CryptNodeKind[T constraints.Integer](v T) CryptNodeKind {
	return CryptNodeKind(v)
}

func (k CryptNodeKind) AssertKind(kinds string) CryptNodeKind {
	for _, kind := range k.Kinds() {
		if strings.ToLower(kinds) == strings.ToLower(kind.String()) {
			return kind
		}
	}
	return InvalidCryptNodeKind
}

func (k CryptNodeKind) String() string {
	switch k {
	case SymmetryNodeKind:
		return "SymmetryNode"
	case AsymmetricalNodeKind:
		return "AsymmetricalNode"
	case HashNodeKind:
		return "HashNode"
	case EncodingNodeKind:
		return "EncodingNode"
	case ToolNodeKind:
		return "ToolNode"
	default:
		return "InvalidCryptNodeKind"
	}
}

func (k CryptNodeKind) Keys() []string {
	return []string{
		"SymmetryNode",
		"AsymmetricalNode",
		"HashNode",
		"EncodingNode",
		"ToolNode",
		"InvalidCryptNodeKind",
	}
}

func (k CryptNodeKind) Kinds() []CryptNodeKind {
	return []CryptNodeKind{
		SymmetryNodeKind,
		AsymmetricalNodeKind,
		HashNodeKind,
		EncodingNodeKind,
		ToolNodeKind,
		InvalidCryptNodeKind,
	}
}

func (k CryptNodeKind) SvgFileName() string {
	switch k {
	case SymmetryNodeKind:
		return "SymmetryNode"
	case AsymmetricalNodeKind:
		return "AsymmetricalNode"
	case HashNodeKind:
		return "HashNode"
	case EncodingNodeKind:
		return "EncodingNode"
	case ToolNodeKind:
		return "ToolNode"
	default:
		return "InvalidCryptNodeKind"
	}
}
