package main

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type EncodingKind byte

const (
	Base64Kind EncodingKind = iota
	Base32Kind
	GzipKind
	InvalidEncodingKind
)

func ConvertInteger2EncodingKind[T constraints.Integer](v T) EncodingKind {
	return EncodingKind(v)
}

func (k EncodingKind) AssertKind(kinds string) EncodingKind {
	for _, kind := range k.Kinds() {
		if strings.ToLower(kinds) == strings.ToLower(kind.String()) {
			return kind
		}
	}
	return InvalidEncodingKind
}

func (k EncodingKind) String() string {
	switch k {
	case Base64Kind:
		return "Base64"
	case Base32Kind:
		return "Base32"
	case GzipKind:
		return "Gzip"
	default:
		return "InvalidEncodingKind"
	}
}

func (k EncodingKind) Keys() []string {
	return []string{
		"Base64",
		"Base32",
		"Gzip",
		"InvalidEncodingKind",
	}
}

func (k EncodingKind) Kinds() []EncodingKind {
	return []EncodingKind{
		Base64Kind,
		Base32Kind,
		GzipKind,
		InvalidEncodingKind,
	}
}

func (k EncodingKind) SvgFileName() string {
	switch k {
	case Base64Kind:
		return "Base64"
	case Base32Kind:
		return "Base32"
	case GzipKind:
		return "Gzip"
	default:
		return "InvalidEncodingKind"
	}
}
