package main

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type HashKind byte

const (
	HmacKind HashKind = iota
	HashAllKind
	InvalidHashKind
)

func ConvertInteger2HashKind[T constraints.Integer](v T) HashKind {
	return HashKind(v)
}

func (k HashKind) AssertKind(kinds string) HashKind {
	for _, kind := range k.Kinds() {
		if strings.ToLower(kinds) == strings.ToLower(kind.String()) {
			return kind
		}
	}
	return InvalidHashKind
}

func (k HashKind) String() string {
	switch k {
	case HmacKind:
		return "Hmac"
	case HashAllKind:
		return "HashAll"
	default:
		return "InvalidHashKind"
	}
}

func (k HashKind) Keys() []string {
	return []string{
		"Hmac",
		"HashAll",
		"InvalidHashKind",
	}
}

func (k HashKind) Kinds() []HashKind {
	return []HashKind{
		HmacKind,
		HashAllKind,
		InvalidHashKind,
	}
}

func (k HashKind) SvgFileName() string {
	switch k {
	case HmacKind:
		return "Hmac"
	case HashAllKind:
		return "HashAll"
	default:
		return "InvalidHashKind"
	}
}
