package main

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type ToolKind byte

const (
	TrimSpaceKind ToolKind = iota
	SwapKind
	RequestHeaderKind
	TimeStampKind
	InvalidToolKind
)

func ConvertInteger2ToolKind[T constraints.Integer](v T) ToolKind {
	return ToolKind(v)
}

func (k ToolKind) AssertKind(kinds string) ToolKind {
	for _, kind := range k.Kinds() {
		if strings.ToLower(kinds) == strings.ToLower(kind.String()) {
			return kind
		}
	}
	return InvalidToolKind
}

func (k ToolKind) String() string {
	switch k {
	case TrimSpaceKind:
		return "TrimSpace"
	case SwapKind:
		return "Swap"
	case RequestHeaderKind:
		return "RequestHeader"
	case TimeStampKind:
		return "TimeStamp"
	default:
		return "InvalidToolKind"
	}
}

func (k ToolKind) Keys() []string {
	return []string{
		"TrimSpace",
		"Swap",
		"RequestHeader",
		"TimeStamp",
		"InvalidToolKind",
	}
}

func (k ToolKind) Kinds() []ToolKind {
	return []ToolKind{
		TrimSpaceKind,
		SwapKind,
		RequestHeaderKind,
		TimeStampKind,
		InvalidToolKind,
	}
}

func (k ToolKind) SvgFileName() string {
	switch k {
	case TrimSpaceKind:
		return "TrimSpace"
	case SwapKind:
		return "Swap"
	case RequestHeaderKind:
		return "RequestHeader"
	case TimeStampKind:
		return "TimeStamp"
	default:
		return "InvalidToolKind"
	}
}
